control:
    speed: 15.0
#    max_turn_rate: 8/15
    initial_position_bound: 250.0
#    beta: 1./3.
    lam: 5.
    sig: 1.
    k1: 1.
    k2: 3.
    r0: 60.
    rho: 1.0

env:
    num_agents_pool: [20]  # Must be specified